### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bukkit/TravelAgent

### ISSUE THREAD

**Issue by Rocologo** [Multiverse/Multiverse-SignPortals#52]
I have updated to newest build on the jenkins server, but it seems that Multiverse-SignPortals has not been updated for SpigotMC 1.14.2 yet? Any plans for this?

[19:29:15] [Server thread/ERROR]: Error occurred while enabling Multiverse-SignPortals v3.0.0-SNAPSHOT-b739 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/TravelAgent
	at com.onarandombox.MultiverseSignPortals.MultiverseSignPortals.onEnable(MultiverseSignPortals.java:55) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.ClassNotFoundException: org.bukkit.TravelAgent
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
	... 10 more

**Comment by axemwa** [comment]
I'm also getting this in 1.14.1

**Comment by Rocologo** [comment]
It is fixed In newest snapshot

**Comment by axemwa** [comment]
K might as well close the issue then i not have the problem anymore either
