### ISSUE TITLE
It spams an error when right clicking

### ISSUE THREAD

**Issue by Ranbee** [Multiverse/Multiverse-SignPortals#56]
Caused by: java.lang.NoSuchFieldError: END_PORTAL_FRAME
        at com.onarandombox.MultiverseCore.listeners.MVPortalListener.portalForm(MVPortalListener.java:74) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor267.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]

**Comment by benwoo1110** [comment]
Can you provide us with more details, such as the full console errors, as well as bother the mv plugins versions and your server version. Thanks!

**Comment by benwoo1110** [comment]
Closing this due to the lack of information.

For 1.8 server, you will need to use an older version of Multiverse - 2.5 should work (not the same as 2.5.0): https://dev.bukkit.org/projects/multiverse-core/files/898527

for sign portals: https://dev.bukkit.org/projects/multiverse-signportals/files/772770
